package org.kyykka.io.forms;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 * A form that should be shown when a game has finished.
 * 
 * @see EndHandler
 * 
 * @author Julius Laitala
 */
public class EndPanel extends javax.swing.JPanel {

    /**
     * Creates new form EndPanel.
     */
    public EndPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        victoryTextLabel = new javax.swing.JLabel();
        playAgainButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        victoryTextLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        victoryTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        victoryTextLabel.setText("INSERT VICTORY TEXT HERE");

        playAgainButton.setText("Play again!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACADEMIC KYYKKA WORLD CUP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addComponent(victoryTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playAgainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addComponent(victoryTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(playAgainButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JLabel victoryTextLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getPlayAgainButton() {
        return playAgainButton;
    }

    public JLabel getVictoryTextLabel() {
        return victoryTextLabel;
    }

}
